In [1]:
import torch
import numpy as np

In [4]:
Scalar_y=torch.tensor(9)
print(Scalar_y)

Vector_y=torch.tensor([1,12,4])
print(Vector_y)

Matrix_y=torch.tensor([[1,4,3],[4,5,6]])
print(Matrix_y)

tensor(9)
tensor([ 1, 12,  4])
tensor([[1, 4, 3],
        [4, 5, 6]])


In [6]:
y=torch.tensor([[1,2,3],[2,6,8],[3,5,7]])

x=torch.tensor([[1,1,4],[5,9,0], [4,5,6]])

print(x.mul(y))
print(x.matmul(y))

tensor([[ 1,  2, 12],
        [10, 54,  0],
        [12, 25, 42]])
tensor([[15, 28, 39],
        [23, 64, 87],
        [32, 68, 94]])


In [11]:
#Compute the derivative of z=x**3 + 5*y**2 + 4*y + 6
x=torch.tensor(data=4., requires_grad=True)
y=torch.tensor(data=5., requires_grad=True)

z=x**3 + 5*y**2 + 4*y + 6

z.backward()

print(x.grad)
print(y.grad)

tensor(48.)
tensor(54.)
